services:
  - type: web
    name: qalam-bot
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y openjdk-11-jdk
      python3 -m pip install -r requirements.txt
    startCommand: python QalamBot.py
    autoDeploy: true

 